[workspace]
authors = ["mattjmeier <matthew.james.meier@gmail.com>"]
channels = ["conda-forge"]
name = "BioTooltipR"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-base = ">=4.6.0,<4.7"
